image:
  repository: mariarti/frontend
  tag: latest

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  host: shop.jasstkn.ru

istio:
  enabled: false

serviceMonitor:
  enabled: false
