name: Deploy
on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
      - uses: helmwave/setup-action@v0.2.0
        name: Install helmwave
        with:
          version: "0.18.0"
      - name: templating helmwave.yml.tpl
        run: helmwave yml
      - name: plan
        run: helmwave build
      - name: deploy
        run: helmwave up --kubedog
